// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CondenseLevel string

const (
	CondenseLevel20 CondenseLevel = "20"
	CondenseLevel40 CondenseLevel = "40"
	CondenseLevel60 CondenseLevel = "60"
	CondenseLevel80 CondenseLevel = "80"
)

func (e *CondenseLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CondenseLevel(s)
	case string:
		*e = CondenseLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for CondenseLevel: %T", src)
	}
	return nil
}

type NullCondenseLevel struct {
	CondenseLevel CondenseLevel `json:"condense_level"`
	Valid         bool          `json:"valid"` // Valid is true if CondenseLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondenseLevel) Scan(value interface{}) error {
	if value == nil {
		ns.CondenseLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CondenseLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondenseLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CondenseLevel), nil
}

type CondensedChapterState string

const (
	CondensedChapterStateNotCondensed     CondensedChapterState = "not_condensed"
	CondensedChapterStateCondensing       CondensedChapterState = "condensing"
	CondensedChapterStateCondensed        CondensedChapterState = "condensed"
	CondensedChapterStateFailedCondensing CondensedChapterState = "failed_condensing"
)

func (e *CondensedChapterState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CondensedChapterState(s)
	case string:
		*e = CondensedChapterState(s)
	default:
		return fmt.Errorf("unsupported scan type for CondensedChapterState: %T", src)
	}
	return nil
}

type NullCondensedChapterState struct {
	CondensedChapterState CondensedChapterState `json:"condensed_chapter_state"`
	Valid                 bool                  `json:"valid"` // Valid is true if CondensedChapterState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCondensedChapterState) Scan(value interface{}) error {
	if value == nil {
		ns.CondensedChapterState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CondensedChapterState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCondensedChapterState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CondensedChapterState), nil
}

type ProcessingState string

const (
	ProcessingStateUploading        ProcessingState = "uploading"
	ProcessingStateSaved            ProcessingState = "saved"
	ProcessingStateProcessingText   ProcessingState = "processing_text"
	ProcessingStateProcessedText    ProcessingState = "processed_text"
	ProcessingStateUploadFailed     ProcessingState = "upload_failed"
	ProcessingStateProcessingFailed ProcessingState = "processing_failed"
)

func (e *ProcessingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingState(s)
	case string:
		*e = ProcessingState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingState: %T", src)
	}
	return nil
}

type NullProcessingState struct {
	ProcessingState ProcessingState `json:"processing_state"`
	Valid           bool            `json:"valid"` // Valid is true if ProcessingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingState) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingState), nil
}

type Book struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	IsbnID          pgtype.Text        `json:"isbn_id"`
	Title           string             `json:"title"`
	Author          pgtype.Text        `json:"author"`
	Tag             pgtype.Text        `json:"tag"`
	NumOfChapters   int32              `json:"num_of_chapters"`
	FileStorageKey  string             `json:"file_storage_key"`
	ProcessingState ProcessingState    `json:"processing_state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Chapter struct {
	ID              pgtype.UUID        `json:"id"`
	BookID          pgtype.UUID        `json:"book_id"`
	ChapterNum      pgtype.Int4        `json:"chapter_num"`
	ChapterTitle    string             `json:"chapter_title"`
	ChapterSubtitle pgtype.Text        `json:"chapter_subtitle"`
	ChapterContent  string             `json:"chapter_content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CondensedChapter struct {
	ID                    pgtype.UUID               `json:"id"`
	ChapterID             pgtype.UUID               `json:"chapter_id"`
	CondenseLevel         CondenseLevel             `json:"condense_level"`
	CondenseContent       pgtype.Text               `json:"condense_content"`
	CondensedChapterState NullCondensedChapterState `json:"condensed_chapter_state"`
	CreatedAt             pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz        `json:"updated_at"`
}

type ReadingProgress struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	CondensedChapterID pgtype.UUID        `json:"condensed_chapter_id"`
	OnPara             int32              `json:"on_para"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
